### PR TITLE
Replace babbies first js with epochs

### PR DESCRIPTION
**Pull request by ghost**
quit being a dunce 
why tf is it two separate funcs, like this is your personal site. it isnt a fuckin api. the use of epochs is totally viable here. also get back to work on mom she keeps stealing my rams and my lawn needs a good clippin. I have no way to get to work and my lawns overgrown. MAKE MOM GIVE ME BACK MY RAMS!!!!

### CODE REVIEW

**Review by z64 — APPROVED** [review]
My name is Richard Stallman and I approve this Pull Request.

image

**Review by BlaineCan — CHANGES_REQUESTED** [review]
No.

**Comment by z64** [comment]
No?

image

**Comment by ghost** [comment]
linus torbal will donate $1000 to the itchy tick foundation to help you fight the 3 yaks and a dog if you accept this pull request sir. 
ballmer-money

**Comment by BlaineCan** [comment]
> linus torbal will donate $1000 to the itchy tick foundation to help you fight the 3 yaks and a dog if you accept this pull request sir.
> ballmer-money

@sgear256 You selected the wrong Ballmer, sir. This is what you were looking for. 
better-ballmer

**Review by BlaineCan — APPROVED** [review]
seemsgood

**Pull request merged**
